### ISSUE TITLE
라이브러리 사용법 질문있습니다..

### ISSUE THREAD

**Issue by HyunJunMo** [getCurrentThread/unoffical-soop-chat-api#3]
라이브러리 클론하고나서 빌드하고 lib.jar 을 따로 종속성 추가하란것이
이 라이브러리 프로젝트에 하는건지..
 아니면 라이브러리를 사용하는 프로젝트 종속성에 추가하는건가요 ?
 
 아직 라이브러리 많이 안써봐서 아직도 개념을 모르겠네요 ㅋㅋ ㅜㅜ

**Comment by getCurrentThread** [comment]
구분해서 설명드리겠습니다:

1. 라이브러리 사용하는 입장:
- 우선적으로 README.md 를 참고하셔서 라이브러리를 빌드하여 lib.jar 파일을 생성하셔야 합니다
- 이 라이브러리를 사용하려는 프로젝트에서 lib.jar를 종속성으로 추가하셔야 합니다
- 예시) 당신의 프로젝트의 build.gradle:
```gradle
dependencies {
    implementation files('libs/unofficial-soop-chat-api.jar')
}
```

2. 라이브러리 개발하는 입장:
- 이 프로젝트를 클론해서 직접 수정/개발하시려는 경우에는 별도 jar 추가 불필요
- 그냥 프로젝트를 열고 코드를 수정하면 됩니다

현재는 라이브러리를 "사용"하시려는 것 같으니 1번 방법을 따르시면 됩니다.

(+추가) 현재 해당 라이브러리의 종속성이 복잡하지 않으니, 
패키지 그 자체를 복사하셔서 사용하길 원하시는 
프로젝트에 고스란히 붙여서 사용하는 방법도 있습니다. :)

**Comment by getCurrentThread** [comment]
질문 사항 해소 되셨으면 Close Issue 부탁드립니다 🙏
